export {default as Navbar} from "./shared/Navbar"
export {default as OwnerCta } from "./CTA/ownerCta"
export {default as Footer} from "./shared/Footer"
export {default as Header} from "./Home/header"
export {default as HomeSectionTitle} from "./Home/HomeSectionTitle"
export {default as CatagoryCard} from "./Home/catagoryCard"
export {default as HouseCard} from "./HousCard/houseCard"
export {default as PopularCity} from "./Home/pupularCity"
export {default as TourCard} from "./Home/Tour"
export {default as MediumHouse} from "./HousCard/MediumHomeCard"
export {default as Stats} from "./Home/Stats"
export {default as Process} from "./Home/Process"
export {default as TestiMonials} from "./Home/Testimonials"