import { FaCcDinersClub, FaClock, FaFireExtinguisher, FaIntercom, FaParking, FaRunning, FaSwimmingPool, FaWindowRestore } from "react-icons/fa";
import { GiCctvCamera, GiElevator, GiTennisCourt } from "react-icons/gi";
import { CgGames, CgGym, CgTrack } from "react-icons/cg";
import { GrSecure } from "react-icons/gr";
import { BsCloudRain } from "react-icons/bs";
import { FcLandscape } from "react-icons/fc";
import { RiCommunityFill, RiCommunityLine } from "react-icons/ri";
import { AiOutlineWifi } from "react-icons/ai";
import { MdLocalParking } from "react-icons/md";
// import { SiAstro } from "react-icons/si";

export const availableAmenities = [
  // { name: "Swimming Pool", icon: FaSwimmingPool },
  // { name: "Gymnasium", icon: CgGym },
  { name: "Under Ground Drainage", icon: CgGym },
  // { name: "Clubhouse", icon:FaCcDinersClub },
  { name: "Security", icon: GrSecure  },
  { name: "Parking", icon: FaParking},
  { name: "Lift", icon: GiElevator },
  // { name: "Rainwater Harvesting", icon: BsCloudRain},
  { name: "Muncipla Water Connection", icon: BsCloudRain},
  { name: "Intercom", icon: FaIntercom },
  // { name: "Fire Safety", icon: FaFireExtinguisher },
  // { name: "Maintenance Staff", icon: FaWindowRestore },
  { name: "24x7 Water Supply", icon: FaClock },
  { name: "CCTV Surveillance", icon: GiCctvCamera },
  // { name: "Landscaped Gardens", icon: FcLandscape },
  // { name: "Multipurpose Court", icon: GiTennisCourt},
  // { name: "Jogging Track", icon: FaRunning },
  // { name: "Indoor Games", icon: CgGames },
  // { name: "Community Hall", icon: RiCommunityFill },
  // { name: "Gated Community", icon: RiCommunityLine },
  { name: "Wi-Fi Connectivity", icon:AiOutlineWifi },
  { name: "Car Parking", icon: MdLocalParking},
  { name: "Vastu Compliant", icon: RiCommunityLine },
  // { name: "Intercom", icon: RiCommunityLine },
  { name: "Solar Water Heater", icon: FaFireExtinguisher },
  // { name: "Senior Citizen Area", icon: "" },
  // { name: "Shopping Center", icon: "" },
  // { name: "Yoga/Meditation Area", icon: "" },
  // { name: "Badminton Court", icon: "" },
  // { name: "Basketball Court", icon: "" },
  // { name: "Squash Court", icon: "" },
  // { name: "Tennis Court", icon: "" },
  // { name: "Cricket Pitch", icon: "" },
  // { name: "Skating Rink", icon: "" },
  // { name: "Cafeteria", icon: "" },
  // { name: "Library", icon: "" },
  // { name: "Theatre", icon: "" },
  // { name: "Banquet Hall", icon: "" },
  // { name: "Guest Accommodation", icon: "" },
  // { name: "ATM", icon: "" },
  // { name: "Laundry Service", icon: "" },
  // { name: "Barbecue Area", icon: "" },
  // { name: "Cycling & Jogging Track", icon: "" },
  // { name: "Pet Area", icon: "" },
  { name: "Water Softner Plant", icon: BsCloudRain },
  // { name: "Piped Gas", icon: "" },
  // { name: "Waste Disposal", icon: "" },
  // { name: "Central AC", icon: "" },
  // { name: "Central Heating", icon: "" },
  // { name: "Pre-school/Daycare", icon: "" },
  // { name: "Medical Facilities", icon: "" },
  // { name: "Pet Friendly", icon: "" },
  // { name: "Vaastu Compliant", icon: "" },
  // { name: "RO Water System", icon: "" },
  // { name: "DTH Television Facility", icon: "" },
  // { name: "Conference Room", icon: "" },
  // { name: "Workspaces", icon: "" },
  // { name: "Waiting Lounge", icon: "" },
  // { name: "Shopping Mall", icon: "" },
  // { name: "Food Court", icon: "" },
  // { name: "Multiplex", icon: "" },
  // { name: "Terrace Garden", icon: "" },
  // { name: "Sewage Treatment Plant", icon: "" },
  // { name: "Bar/Lounge", icon: "" },
  // { name: "Mini Theatre", icon: "" },
  // { name: "Party Lawn", icon: "" },
  // { name: "Amphitheatre", icon: "" },
  // { name: "Jacuzzi", icon: "" },
  // { name: "Salon", icon: "" },
  // { name: "Sauna", icon: "" },
  // { name: "Spa", icon: "" },
  // { name: "Indoor Jacuzzi", icon: "" },
  // { name: "Outdoor Jacuzzi", icon: "" },
  // { name: "Private Pool", icon: "" },
  // { name: "Golf Course", icon: "" },
  // { name: "Horse Riding Arena", icon: "" },
  // { name: "Helipad", icon: "" },
  // { name: "Golf View", icon: "" },
  // { name: "Open Space", icon: "" },
  // { name: "Aerobics Room", icon: "" },
  // { name: "Garden", icon: "" },
  // { name: "ATM/Cafeteria", icon: "" },
  // { name: "Football", icon: "" },
  // { name: "Volleyball", icon: "" },
  // { name: "School", icon: "" },
  // { name: "Hospital", icon: "" },
  // { name: "Temple", icon: "" },
  // { name: "Pantry", icon: "" },
  // { name: "ATM/Bank", icon: "" },
  // { name: "Lobby Area", icon: "" },
  // { name: "Business Center", icon: "" },
  // { name: "Pre-School", icon: "" },
  // { name: "Restaurant", icon: "" },
  // { name: "Staff Quarter", icon: "" },
  // { name: "Billiards Room", icon: "" },
  // { name: "Kids Pool", icon: "" },
  // { name: "Meditation Center", icon: "" },
  // { name: "Valet Parking", icon: "" },
  // { name: "Golf Simulator", icon: "" },
  // { name: "Kids Area", icon: "" },
  // { name: "Carrom Board", icon: "" },
  // { name: "Multipurpose Lawn", icon: "" },
  // { name: "Dance Studio", icon: "" },
  // { name: "Reading Lounge", icon: "" },
  // { name: "Terrace", icon: "" },
  // { name: "Sculpture Garden", icon: "" },
  // { name: "Rock Climbing", icon: BsCloudRain },
  // { name: "Karaoke", icon: "" },
  // { name: "Bar", icon: "" },
  // { name: "Toddler Pool", icon: "" },
  // { name: "Conference Hall", icon: "" },
  // { name: "Jogging", icon: "" },
  // { name: "Cycling", icon: "" },
  { name: "Power Backup", icon: BsCloudRain },
  // { name: "Health Facilities", icon: "" },
  { name: "Childrens Play Area", icon: "" },
];
export const adminAvailableAmenities = [
  { name: "Swimming Pool", icon: FaSwimmingPool },
  { name: "Gymnasium", icon: CgGym },
  { name: "Under Ground Drainage", icon: CgGym },
  { name: "Clubhouse", icon:FaCcDinersClub },
  { name: "Security", icon: GrSecure  },
  { name: "Parking", icon: FaParking},
  { name: "Lift", icon: GiElevator },
  { name: "Rainwater Harvesting", icon: BsCloudRain},
  { name: "Muncipla Water Connection", icon: BsCloudRain},
  { name: "Intercom", icon: FaIntercom },
  { name: "Fire Safety", icon: FaFireExtinguisher },
  { name: "Maintenance Staff", icon: FaWindowRestore },
  { name: "24x7 Water Supply", icon: FaClock },
  { name: "CCTV Surveillance", icon: GiCctvCamera },
  { name: "Landscaped Gardens", icon: FcLandscape },
  { name: "Multipurpose Court", icon: GiTennisCourt},
  { name: "Jogging Track", icon: FaRunning },
  { name: "Indoor Games", icon: CgGames },
  { name: "Community Hall", icon: RiCommunityFill },
  { name: "Gated Community", icon: RiCommunityLine },
  { name: "Wi-Fi Connectivity", icon:AiOutlineWifi },
  { name: "Car Parking", icon: MdLocalParking},
  { name: "Vastu Compliant", icon: RiCommunityLine },
  { name: "Intercom", icon: RiCommunityLine },
  { name: "Solar Water Heater", icon: FaFireExtinguisher },
  { name: "Senior Citizen Area", icon: "" },
  { name: "Shopping Center", icon: "" },
  { name: "Yoga/Meditation Area", icon: "" },
  { name: "Badminton Court", icon: "" },
  { name: "Basketball Court", icon: "" },
  { name: "Squash Court", icon: "" },
  { name: "Tennis Court", icon: "" },
  { name: "Cricket Pitch", icon: "" },
  { name: "Skating Rink", icon: "" },
  { name: "Cafeteria", icon: "" },
  { name: "Library", icon: "" },
  { name: "Theatre", icon: "" },
  { name: "Banquet Hall", icon: "" },
  { name: "Guest Accommodation", icon: "" },
  { name: "ATM", icon: "" },
  { name: "Laundry Service", icon: "" },
  { name: "Barbecue Area", icon: "" },
  { name: "Cycling & Jogging Track", icon: "" },
  { name: "Pet Area", icon: "" },
  { name: "Water Softner Plant", icon: BsCloudRain },
  { name: "Piped Gas", icon: "" },
  { name: "Waste Disposal", icon: "" },
  { name: "Central AC", icon: "" },
  { name: "Central Heating", icon: "" },
  { name: "Pre-school/Daycare", icon: "" },
  { name: "Medical Facilities", icon: "" },
  { name: "Pet Friendly", icon: "" },
  { name: "Vaastu Compliant", icon: "" },
  { name: "RO Water System", icon: "" },
  { name: "DTH Television Facility", icon: "" },
  { name: "Conference Room", icon: "" },
  { name: "Workspaces", icon: "" },
  { name: "Waiting Lounge", icon: "" },
  { name: "Shopping Mall", icon: "" },
  { name: "Food Court", icon: "" },
  { name: "Multiplex", icon: "" },
  { name: "Terrace Garden", icon: "" },
  { name: "Sewage Treatment Plant", icon: "" },
  { name: "Bar/Lounge", icon: "" },
  { name: "Mini Theatre", icon: "" },
  { name: "Party Lawn", icon: "" },
  { name: "Amphitheatre", icon: "" },
  { name: "Jacuzzi", icon: "" },
  { name: "Salon", icon: "" },
  { name: "Sauna", icon: "" },
  { name: "Spa", icon: "" },
  { name: "Indoor Jacuzzi", icon: "" },
  { name: "Outdoor Jacuzzi", icon: "" },
  { name: "Private Pool", icon: "" },
  { name: "Golf Course", icon: "" },
  { name: "Horse Riding Arena", icon: "" },
  { name: "Helipad", icon: "" },
  { name: "Golf View", icon: "" },
  { name: "Open Space", icon: "" },
  { name: "Aerobics Room", icon: "" },
  { name: "Garden", icon: "" },
  { name: "ATM/Cafeteria", icon: "" },
  { name: "Football", icon: "" },
  { name: "Volleyball", icon: "" },
  { name: "School", icon: "" },
  { name: "Hospital", icon: "" },
  { name: "Temple", icon: "" },
  { name: "Pantry", icon: "" },
  { name: "ATM/Bank", icon: "" },
  { name: "Lobby Area", icon: "" },
  { name: "Business Center", icon: "" },
  { name: "Pre-School", icon: "" },
  { name: "Restaurant", icon: "" },
  { name: "Staff Quarter", icon: "" },
  { name: "Billiards Room", icon: "" },
  { name: "Kids Pool", icon: "" },
  { name: "Meditation Center", icon: "" },
  { name: "Valet Parking", icon: "" },
  { name: "Golf Simulator", icon: "" },
  { name: "Kids Area", icon: "" },
  { name: "Carrom Board", icon: "" },
  { name: "Multipurpose Lawn", icon: "" },
  { name: "Dance Studio", icon: "" },
  { name: "Reading Lounge", icon: "" },
  { name: "Terrace", icon: "" },
  { name: "Sculpture Garden", icon: "" },
  { name: "Rock Climbing", icon: BsCloudRain },
  { name: "Karaoke", icon: "" },
  { name: "Bar", icon: "" },
  { name: "Toddler Pool", icon: "" },
  { name: "Conference Hall", icon: "" },
  { name: "Jogging", icon: "" },
  { name: "Cycling", icon: "" },
  { name: "Power Backup", icon: BsCloudRain },
  { name: "Health Facilities", icon: "" },
  { name: "Childrens Play Area", icon: "" },
];
